src/main/java/uk/gov/justice/digital/config/JobParameters.java, src/test/java/uk/gov/justice/digital/config/JobParametersTest.java, src/test/java/uk/gov/justice/digital/zone/RawZoneTest.java
* add `dpr` prefix to namespace our job parameters
* updated job parameters test
*Note* This a breaking change and job configurations in AWS will need to be updated after this is merged.
=> DPR-345 add dpr prefix to job parameter names

.circleci/config.yml
Fix Placeholder Script to Python
=> ORB version upgrade

src/main/java/uk/gov/justice/digital/domain/DomainExecutor.java, src/main/java/uk/gov/justice/digital/service/DomainSchemaService.java
=> DPR-219:Added schema classes to create, update and delete

build.gradle, src/main/java/uk/gov/justice/digital/domain/DomainExecutor.java, src/main/java/uk/gov/justice/digital/job/DomainRefreshJob.java, src/main/java/uk/gov/justice/digital/service/DomainSchemaService.java, src/main/java/uk/gov/justice/digital/service/DomainService.java, src/test/java/uk/gov/justice/digital/domain/DomainExecutorTest.java, src/test/java/uk/gov/justice/digital/service/DomainServiceTest.java
=> DPR-374:Refactoring changes

build.gradle, src/main/java/uk/gov/justice/digital/config/JobParameters.java, src/main/java/uk/gov/justice/digital/domain/DomainExecutor.java, src/main/java/uk/gov/justice/digital/exception/DomainExecutorException.java, src/main/java/uk/gov/justice/digital/exception/DomainSchemaException.java, src/main/java/uk/gov/justice/digital/service/DomainSchemaService.java, src/test/java/uk/gov/justice/digital/domain/DomainExecutorTest.java, src/test/java/uk/gov/justice/digital/service/DomainSchemaServiceTest.java, src/test/java/uk/gov/justice/digital/service/DomainServiceTest.java, src/test/java/uk/gov/justice/digital/service/SchemaTestHelpers.java
DPR-418 changes included in DPR-374 now
=> DPR-374:Refactoring changes taken from DPR-418

build.gradle, src/main/java/uk/gov/justice/digital/domain/DomainExecutor.java, src/main/java/uk/gov/justice/digital/domain/model/HiveTableIdentifier.java, src/main/java/uk/gov/justice/digital/domain/model/TableDefinition.java, src/main/java/uk/gov/justice/digital/domain/model/TableIdentifier.java, src/main/java/uk/gov/justice/digital/domain/model/TableInfo.java, src/main/java/uk/gov/justice/digital/exception/DomainExecutorException.java, src/main/java/uk/gov/justice/digital/exception/DomainSchemaException.java, src/main/java/uk/gov/justice/digital/service/DataStorageService.java, src/main/java/uk/gov/justice/digital/service/DomainSchemaService.java, src/main/java/uk/gov/justice/digital/service/DomainService.java, src/main/java/uk/gov/justice/digital/service/SourceReferenceService.java, src/test/java/uk/gov/justice/digital/config/BaseSparkTest.java, src/test/java/uk/gov/justice/digital/config/ResourceLoader.java, src/test/java/uk/gov/justice/digital/domain/DomainExecutorTest.java, src/test/java/uk/gov/justice/digital/service/DomainSchemaServiceTest.java, src/test/java/uk/gov/justice/digital/service/DomainServiceTest.java, src/test/java/uk/gov/justice/digital/service/SparkTestHelpers.java
* renamed `TableInfo` to `HiveTableIdentifier` which should better reflect the intent of this class
* simplified `ResourceLoader`
* cleaned up `DomainExecutorTest` removing duplication where possible, simplified `areEqual` and used `val` keyword instead of explicit type declarations
* other minor tidyups
=> DPR-422 Jobs code refactor pass 2

src/main/java/uk/gov/justice/digital/domain/DomainExecutor.java, src/main/java/uk/gov/justice/digital/service/DataStorageService.java, src/main/java/uk/gov/justice/digital/service/DomainSchemaService.java, src/test/java/uk/gov/justice/digital/domain/DomainExecutorTest.java, src/test/java/uk/gov/justice/digital/service/DataStorageServiceTest.java
=> DPR-464 Fix insert and delete errors in creating hive metadata tables.

src/main/java/uk/gov/justice/digital/client/glue/GlueSchemaClient.java, src/main/java/uk/gov/justice/digital/config/JobArguments.java, src/test/java/uk/gov/justice/digital/client/glue/GlueSchemaClientTest.java, src/test/java/uk/gov/justice/digital/config/JobArgumentsTest.java
* introduce GlueSchemaClient and tests
* add new job argument `dpr.contract.registryName`
=> DPR-478 integrate with glue schema registry

src/main/java/uk/gov/justice/digital/job/filter/field/SparkTimestampFieldFilter.java, src/main/java/uk/gov/justice/digital/job/udf/JsonValidator.java
* revise validator logging to always show differences
* prevent NPE noise when parsing datetimes
=> NOJIRA revise validator logging to always show differences and fix NPE noise in the filters

src/it/java/uk/gov/justice/digital/zone/StructuredZoneIntegrationTest.java, src/test/java/uk/gov/justice/digital/zone/StructuredZoneTest.java
This PR:
- Adds tests to check that null columns are kept by the structured zone in `StructuredZoneTest.java`
=> DPR-311: Assert null columns are kept by structured zone

build.gradle, src/main/java/uk/gov/justice/digital/provider/SparkSessionProvider.java, src/main/java/uk/gov/justice/digital/service/DataStorageService.java, src/main/java/uk/gov/justice/digital/writer/Writer.java, src/main/java/uk/gov/justice/digital/zone/curated/CuratedZone.java, src/main/java/uk/gov/justice/digital/zone/structured/StructuredZone.java
This PR reviews the logs and also some minor refactoring.
=> DPR-618: Review logs and minor refactoring

build.gradle, src/main/java/uk/gov/justice/digital/job/DataHubJob.java, src/main/java/uk/gov/justice/digital/zone/curated/CuratedZone.java, src/main/java/uk/gov/justice/digital/zone/curated/CuratedZoneCDC.java, src/main/java/uk/gov/justice/digital/zone/curated/CuratedZoneLoad.java, src/main/java/uk/gov/justice/digital/zone/raw/RawZone.java, src/main/java/uk/gov/justice/digital/zone/structured/StructuredZone.java, src/main/java/uk/gov/justice/digital/zone/structured/StructuredZoneCDC.java, src/main/java/uk/gov/justice/digital/zone/structured/StructuredZoneLoad.java
This PR fixes the dedupe login in getTablesInBatch and also improves the logs so they are distinguishable per zone and operation type.
=> DPR-622: Fix bug in get tables in batch and improve logs

build.gradle, src/it/java/uk/gov/justice/digital/service/DataStorageServiceIntegrationTest.java, src/it/java/uk/gov/justice/digital/service/MaintenanceServiceCompactionIntegrationTest.java, src/it/java/uk/gov/justice/digital/service/MaintenanceServiceVacuumIntegrationTest.java, src/it/java/uk/gov/justice/digital/test/DeltaTablesTestBase.java, src/it/java/uk/gov/justice/digital/test/SparkTestHelpers.java, src/main/java/uk/gov/justice/digital/config/JobArguments.java, src/main/java/uk/gov/justice/digital/job/CompactionJob.java, src/main/java/uk/gov/justice/digital/job/VacuumJob.java, src/main/java/uk/gov/justice/digital/service/DataStorageService.java, src/main/java/uk/gov/justice/digital/service/MaintenanceService.java, src/test/java/uk/gov/justice/digital/service/DataStorageServiceTest.java, src/test/java/uk/gov/justice/digital/service/MaintenanceServiceTest.java
Implement jobs.
Automated tests.
Ensure new jobs stick to pre-existing service layers.
=> DPR-635 Maintenance CompactionJob and VacuumJob.

src/main/java/uk/gov/justice/digital/job/DataHubJob.java, src/main/java/uk/gov/justice/digital/zone/curated/CuratedZoneCDC.java, src/main/java/uk/gov/justice/digital/zone/curated/CuratedZoneLoad.java, src/main/java/uk/gov/justice/digital/zone/raw/RawZone.java, src/main/java/uk/gov/justice/digital/zone/structured/StructuredZoneCDC.java, src/main/java/uk/gov/justice/digital/zone/structured/StructuredZoneLoad.java
To save cost. This sets only the info logs we care about to WARN level.
=> DPR-622: Update log levels

build.gradle, src/it/java/uk/gov/justice/digital/domain/DomainExecutorIntegrationTest.java, src/it/java/uk/gov/justice/digital/service/DataStorageServiceIntegrationTest.java, src/it/java/uk/gov/justice/digital/service/MaintenanceServiceCompactionIntegrationTest.java, src/it/java/uk/gov/justice/digital/service/MaintenanceServiceVacuumIntegrationTest.java, src/it/java/uk/gov/justice/digital/test/SparkTestHelpers.java, src/main/java/uk/gov/justice/digital/config/JobArguments.java, src/main/java/uk/gov/justice/digital/service/DataStorageService.java, src/test/java/uk/gov/justice/digital/domain/DomainExecutorTest.java, src/test/java/uk/gov/justice/digital/service/DataStorageServiceTest.java, src/test/java/uk/gov/justice/digital/test/SparkTestHelpers.java
- Adds retry with backoff to DataStorageService calls that are in danger of failing due to subclasses of DeltaConcurrentModificationException
- Does make the changes so that eventual failures are written to exceptions - this will come in another PR
=> DPR2-151 backoff retry

src/main/java/uk/gov/justice/digital/service/HiveSchemaService.java, src/main/java/uk/gov/justice/digital/zone/structured/StructuredZoneCDCS3.java, src/test/java/uk/gov/justice/digital/service/HiveSchemaServiceTest.java
This PR uses a symlink Hive table for the structured and curated tables.
=> DPR2-209: Use symlinked delta tables for structured and curated

src/main/java/uk/gov/justice/digital/client/s3/S3DataProvider.java, src/test/java/uk/gov/justice/digital/client/s3/S3DataProviderTest.java
- In the dev environment Spark throws the SparkException indicating the incompatible schema and is handled as per the last PR.
- In the test environment, presumably due to the slightly different test data mixed in with my test case data, Spark is wrapping the exception in another one.
- This PR handles the wrapped case by checking the cause.
=> DPR2-210: Handle nested incompatible schema exception.

src/main/java/uk/gov/justice/digital/client/s3/S3ConfigReaderClient.java
This PR updates the config file location to
`s3://dpr-glue-jobs-<environment>/configs/<domain>/table-config.json`
=> DPR2-258: Update config file location

src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
I noticed this minor thing while reviewing the code for DPR2-34.
=> DPR2-34 Parameterise test rather than use loop

src/main/java/uk/gov/justice/digital/client/glue/GlueClient.java, src/main/java/uk/gov/justice/digital/common/CommonDataFields.java, src/main/java/uk/gov/justice/digital/datahub/model/SourceReference.java, src/main/java/uk/gov/justice/digital/service/HiveTableService.java, src/main/java/uk/gov/justice/digital/service/SourceReferenceService.java, src/test/java/uk/gov/justice/digital/client/glue/GlueClientTest.java, src/test/java/uk/gov/justice/digital/service/HiveTableServiceTest.java, src/test/java/uk/gov/justice/digital/test/Fixtures.java
This PR adds the table params documented at https://github.com/moj-analytical-services/dmet-prisons/discussions/12
=> DPR2-712: Add table params

src/it/java/uk/gov/justice/digital/job/cdc/TableStreamingQueryIT.java, src/main/java/uk/gov/justice/digital/common/retry/RetryConfig.java, src/main/java/uk/gov/justice/digital/common/retry/RetryPolicyBuilder.java, src/main/java/uk/gov/justice/digital/service/DataStorageService.java, src/main/java/uk/gov/justice/digital/service/S3FileService.java, src/test/java/uk/gov/justice/digital/job/CreateReloadDiffJobTest.java, src/test/java/uk/gov/justice/digital/job/HiveTableCreationJobTest.java, src/test/java/uk/gov/justice/digital/job/SwitchHiveTableJobTest.java, src/test/java/uk/gov/justice/digital/job/batchprocessing/ReloadDiffProcessorTest.java, src/test/java/uk/gov/justice/digital/job/cdc/TableStreamingQueryTest.java, src/test/java/uk/gov/justice/digital/service/DataStorageServiceTest.java, src/test/java/uk/gov/justice/digital/service/HiveTableServiceTest.java, src/test/java/uk/gov/justice/digital/service/S3FileServiceTest.java, src/test/java/uk/gov/justice/digital/service/SourceReferenceServiceTest.java, src/test/java/uk/gov/justice/digital/test/SparkTestHelpers.java, src/test/java/uk/gov/justice/digital/test/TestHelpers.java
This PR retries a S3 file copy/delete when an error occurs. This is required to prevent throttling failures from terminating the pipeline.
`com.amazonaws.services.s3.model.AmazonS3Exception: Please reduce your request rate. (Service: Amazon S3; Status Code: 503;`
=> DPR2-1240: Retry failed file transfers

src/it/java/uk/gov/justice/digital/service/MaintenanceServiceCompactionIntegrationTest.java, src/it/java/uk/gov/justice/digital/service/MaintenanceServiceVacuumIntegrationTest.java, src/main/java/uk/gov/justice/digital/job/CompactionJob.java, src/main/java/uk/gov/justice/digital/job/VacuumJob.java, src/main/java/uk/gov/justice/digital/service/MaintenanceService.java, src/test/java/uk/gov/justice/digital/job/CompactionJobTest.java, src/test/java/uk/gov/justice/digital/job/VacuumJobTest.java, src/test/java/uk/gov/justice/digital/service/MaintenanceServiceTest.java
This PR truly isolates the maintenance job to the configured domains by performing the maintenance task on the table folder only.
=> DPR2-1562: Isolate maintenance jobs To each domain

src/it/java/uk/gov/justice/digital/service/DataStorageServiceIntegrationTest.java, src/main/java/uk/gov/justice/digital/job/CompactionJob.java, src/main/java/uk/gov/justice/digital/job/VacuumJob.java, src/main/java/uk/gov/justice/digital/service/DataStorageService.java, src/test/java/uk/gov/justice/digital/job/CompactionJobTest.java, src/test/java/uk/gov/justice/digital/job/VacuumJobTest.java
This PR fixes the path in the maintenance job from:
- s3://bucket-name/noms/nomis/agency_locations
to
- s3://bucket-name/noms/agency_locations
```
2024-12-10 10:08:36.999 ERROR uk.gov.justice.digital.service.DataStorageService: Exception encountered when listing delta tables at root path: s3://dpr-structured-zone-preproduction/nomis/nomis/agency_internal_locations
```
=> DPR2-1562: Fix path in maintenance jobs

src/main/java/uk/gov/justice/digital/client/s3/S3ObjectClient.java, src/main/java/uk/gov/justice/digital/service/S3FileService.java, src/test/java/uk/gov/justice/digital/client/s3/S3ClientTest.java, src/test/java/uk/gov/justice/digital/service/S3FileServiceTest.java
This PR optimises the deletion of files by using the S3 DeleteObjects API which allows for deleting up to 1000 objects per request.
=> DPR2-1561: Delete s3 objects in batch

src/main/java/uk/gov/justice/digital/client/s3/S3ObjectClient.java, src/test/java/uk/gov/justice/digital/client/s3/S3ClientTest.java
This PR fixes a bug when handling the response of the `getDeletedObjects()` S3 API.
As per the [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html):
>The operation supports two modes for the response: verbose and quiet. By default, the operation uses verbose mode in which the response includes the result of deletion of each key in your request. In quiet mode the response includes only keys where the delete operation encountered an error. For a successful deletion in a quiet mode, the operation does not return any information about the delete in the response body.
Since we are using quiet mode (i.e. setting `withQuite(true)`) the return of `getDeletedObjects()` should contain only the failed objects.
=> DPR2-1561: Correctly interpret deleteObjects response

.github/workflows/add-coverage-to-pr.yml
This PR upgrades gradle/gradle-build-action from v2 to v3
=> DPR2-1996: Upgrade to gradle/gradle-build-action@v3
