ministryofjustice/digital-prison-reporting-jobs

- build.gradle
* Glue already adds Spark 3.3.0 to the classpath so we can remove spark-core from the jar which is pulled in transitively by the kinesis asl streaming library
* This reduces the jar size significantly from approx 160MiB to 36MiB
> DPR-319 remove spark-core from kinesis-asl dep reducing jar size

- bin/check-fields
- src/main/java/uk/gov/justice/digital/job/DataHubJob.java
- src/main/java/uk/gov/justice/digital/zone/StructuredZone.java
- src/main/resources/schemas/oms_owner.agency_locations.schema.json
- src/main/resources/schemas/oms_owner.offender_bookings.schema.json
- src/test/java/uk/gov/justice/digital/converter/dms/DMS_3_4_6_ConverterTest.java
- src/test/java/uk/gov/justice/digital/job/udf/JsonValidatorTest.java
- src/test/resources/data/dms_data.json
- src/test/resources/data/dms_record.json
* updated nomis table schemas where latest T3 data differs (new fields or field renames)
* revised schema validation to ensure the parsed json includes null fields which matches the incoming json ensuring the basic structural match works correctly
* fixed an issue with parsing JSON from a file which caused the DMS test to fail after merging (we have a json format trigger that adds newlines - so the test now handles multiline json)
* added a script that compares the fields in a given schema and corresponding dms json file highlighting any differences (which came in handy when I was investigating validation failures after fixing the issue with null fields)
* other minor tidy ups e.g. removing unused imports etc..
> DPR-367 fix schema parsing issues

- scripts/push-jar
- scripts/start-and-tail-job
- scripts/tail-glue-logs
Added the following scripts
* push-jar - builds and pushes the project jar to an s3 folder uri
* tail-glue-logs - tail the logs for a given job name
* start-and-tail-job - starts a given job name and then tails the logs
> NOJIRA add helper scripts for working with aws glue jobs

- src/main/java/uk/gov/justice/digital/client/dynamodb/DynamoDBClient.java
- src/main/java/uk/gov/justice/digital/domain/DomainExecutor.java
- src/main/java/uk/gov/justice/digital/job/DataHubJob.java
- src/main/java/uk/gov/justice/digital/job/DomainRefreshJob.java
- src/main/java/uk/gov/justice/digital/job/SparkSessionProvider.java
- src/main/java/uk/gov/justice/digital/provider/SparkSessionProvider.java
- src/main/java/uk/gov/justice/digital/repository/DomainRepository.java
- src/main/java/uk/gov/justice/digital/service/DataStorageService.java
- src/main/java/uk/gov/justice/digital/service/DomainService.java
- src/main/java/uk/gov/justice/digital/zone/Zone.java
- src/test/java/uk/gov/justice/digital/config/BaseSparkTest.java
- src/test/java/uk/gov/justice/digital/domain/DomainExecutorTest.java
- src/test/java/uk/gov/justice/digital/service/DomainServiceTest.java
- src/test/java/uk/gov/justice/digital/service/SparkTestHelpers.java
Addresses some of the issues raised in the recent PR that was merged covering
* Job has now become `SparkSessionProvider` which is a singleton that can be wired in by micronaut DI where used
* Other classes that needed to use micronaut DI have been revised so that it's now used to instantiate/wire in dependencies where applicable which necessitated some API changes
* Other minor changes e.g. logging, removing println etc..
Note - this PR introduces some TODOs that can be addressed later since there's some scope for further improvements but this can be addressed later.
> NOJIRA - a little light refactoring

- build.gradle
This change ensures that shadowJar will get triggered when `build` is run in order to create the 'fat' jar with all required dependencies bundled.
> DPR-408 build now depends on shadowJar

- build.gradle
- src/main/java/uk/gov/justice/digital/client/ClientProvider.java
- src/main/java/uk/gov/justice/digital/client/glue/GlueClientProvider.java
- src/main/java/uk/gov/justice/digital/client/glue/JobClient.java
- src/main/java/uk/gov/justice/digital/client/kinesis/KinesisReader.java
- src/main/java/uk/gov/justice/digital/config/JobProperties.java
- src/main/java/uk/gov/justice/digital/config/Properties.java
- src/main/java/uk/gov/justice/digital/domain/model/TableInfo.java
- src/main/java/uk/gov/justice/digital/service/DomainSchemaService.java
- src/main/resources/log4j2.properties
- src/test/java/uk/gov/justice/digital/client/glue/JobClientTest.java
- src/test/java/uk/gov/justice/digital/config/JobPropertiesTest.java
- src/test/java/uk/gov/justice/digital/config/ResourceLoader.java
- src/test/java/uk/gov/justice/digital/domain/DomainExecutorTest.java
- src/test/java/uk/gov/justice/digital/service/DomainSchemaServiceTest.java
- src/test/java/uk/gov/justice/digital/service/DomainServiceTest.java
- src/test/java/uk/gov/justice/digital/service/SparkTestHelpers.java
* introduce `ClientProvider<T>` interface and provide implementation for `AWSGlue` client instance
* revise `JobClient` to use `GlueClientProvider` to obtain an instance of the `AWSGlue` client
* revise `DomainSchemaService` to use `GlueClientProvider`
* revise `Properties` class, now a singleton renamed to `JobProperties` with classes using this now injecting in an instance
* revise tests to provide mock collaborators (in this case for ClientProvider and underlying AWSGlue client instance along with the JobProperties singleton)
* revise `DomainSchemaService` tests to use mocked collaborators including mocked `Dataframe` and `Schema` instances so the test no longer depends on a running spark instance
* other minor changes including some tidying, rename of `saveToDisk` …
> DPR-422 address remaining code quality issues

- .circleci/config.yml
- src/test/java/uk/gov/justice/digital/domain/DomainExecutorTest.java
- src/test/java/uk/gov/justice/digital/service/DomainServiceTest.java
- src/test/java/uk/gov/justice/digital/test/ResourceLoader.java
- src/test/java/uk/gov/justice/digital/test/SchemaTestHelpers.java
- src/test/java/uk/gov/justice/digital/test/SparkTestHelpers.java
* revise build config so we skip the second test run currently active during packaging the jar (this isn't necessary)
* tidied up `DomainServiceTest` removing repetition etc..
* moved test helpers into a separate `test` package
In working on this I tried a few different ways to speed up the test runs, none of which yielded any significant speed ups. The approaches tried were
* persisting data before the tests run
* using pre-loaded tables (the idea was to save on the time it takes to persist)
* using a single spark instance shared across tests
so the changeset is limited to the refactoring I applied before looking into this.
> DPR-422 tidy up DomainService test and speed up builds

- .circleci/config.yml
This fixes an issue with artifact tagging which expects the standard jar to be present as well as the 'fat' jar built by shadowJar.
> DPR-422 ensure both standard jar and fat jar are built

- src/main/java/uk/gov/justice/digital/provider/SparkSessionProvider.java
Removed irrelevant INFO messages.
We should put some visual barrier (eg ============) at start and stop job.
> DPR-452 Fix Spark Logging

- src/main/java/uk/gov/justice/digital/service/DomainSchemaService.java
Replaced schema.table with schema_table, as schema.table is not referenceable from Redshift Spectrum.
Changed the code so it is easy to experiment with different separators (eg $, %, __)
> DPR-465 Replaced schema.table with schema_table

- src/main/java/uk/gov/justice/digital/provider/SparkSessionProvider.java
- src/main/java/uk/gov/justice/digital/zone/StructuredZone.java
* explicitly set log level to INFO
* use micronaut LogLevel enum instead of local strings
* fix naming of `handleInvalidRecords` method
> NOJIRA - reinstate info level logging

- src/main/java/uk/gov/justice/digital/client/dynamodb/DomainDefinitionClient.java
- src/main/java/uk/gov/justice/digital/domain/DomainExecutor.java
- src/main/java/uk/gov/justice/digital/service/DataStorageService.java
- src/main/java/uk/gov/justice/digital/service/DomainService.java
- src/main/java/uk/gov/justice/digital/zone/CuratedZone.java
- src/main/java/uk/gov/justice/digital/zone/RawZone.java
- src/main/java/uk/gov/justice/digital/zone/StructuredZone.java
- src/test/java/uk/gov/justice/digital/client/dynamodb/DomainDefinitionClientTest.java
- src/test/java/uk/gov/justice/digital/domain/DomainExecutorTest.java
- src/test/java/uk/gov/justice/digital/service/DomainServiceTest.java
* introduce separate `doDomainDelete()` method on the executor so we have a clear separation of this functionality with a cleaner API that no-longer means we need to pass nulls in the parameter list
* internalised the dynamo db table name so that the caller is not required to pass this in anymore - this is an internal concern of the client and shouldn't be exposed
* revised the DomainService tests so they actually test the DomainService (not the DomainExecutor which is already tested elsewhere) using mocked collaborators
* revised the public API of the DomainDefinitionClient so the caller simply makes one method call to get a domain definition (getting the result and parsing it are both internal concerns of the client)
* log messages now use consistent language in Zone …
> DPR-478 some refactoring before working on the SourceReferenceService

- build.gradle
- src/main/java/uk/gov/justice/digital/converter/Converter.java
- src/main/java/uk/gov/justice/digital/converter/avro/AvroToSparkSchemaConverter.java
- src/main/java/uk/gov/justice/digital/converter/dms/DMS_3_4_6.java
- src/main/java/uk/gov/justice/digital/job/DataHubJob.java
- src/main/java/uk/gov/justice/digital/zone/CuratedZone.java
- src/main/java/uk/gov/justice/digital/zone/RawZone.java
- src/main/java/uk/gov/justice/digital/zone/StructuredZone.java
- src/test/java/uk/gov/justice/digital/converter/avro/AvroToSparkSchemaConverterTest.java
- src/test/java/uk/gov/justice/digital/converter/dms/DMS_3_4_6_ConverterTest.java
- src/test/java/uk/gov/justice/digital/zone/Fixtures.java
* added converter that takes an avro schema and converts it into a spark schema using the spark-avro support
* added tests to cover conversion of all declared types
* simplified converter so we have an interface with a single method and refactored
> DPR-478 add avro to spark schema converter

- src/main/java/uk/gov/justice/digital/job/udf/JsonValidator.java
- src/test/java/uk/gov/justice/digital/job/udf/JsonValidatorTest.java
* revised the json comparision so we compare the data using Maps which contain the original and parsed data (where the avro schema has been applied)
* validator now reformats datetime strings in the original data where
* the date string contains a `T`indicating that it might be an ISO 8601 date time string
* the time part contains no digits except 0
* otherwise the date value is left as is
* the validator then continues as before comparing the original data with reformatted dates against the parsed data
* this will then allow validation to pass where some dates were originally represented using date times
* test updates to cover the new work
> DPR-521 Allow dates represented as datetimes to pass validation if time value is zeroed

- src/main/java/uk/gov/justice/digital/job/DataHubJob.java
This PR uses the extracted dataframe to create the structured zone data.
This was wrongly changed to use the raw zone data in my previous [PR](https://github.com/ministryofjustice/digital-prison-reporting-jobs/pull/89/files#diff-3a476dcab1d8f8a05ec230340802b150d53cc79770505951e96d4af5ccb2c6d4L93-R69).
> DPR-198: Use extracted dataframe as input to structured zone

- src/it/java/uk/gov/justice/digital/zone/StructuredZoneIntegrationTest.java
- src/main/java/uk/gov/justice/digital/converter/dms/DMS_3_4_6.java
- src/main/java/uk/gov/justice/digital/job/DataHubJob.java
- src/main/java/uk/gov/justice/digital/service/DataStorageService.java
- src/main/java/uk/gov/justice/digital/zone/CuratedZone.java
- src/main/java/uk/gov/justice/digital/zone/FilteredZone.java
- src/main/java/uk/gov/justice/digital/zone/StructuredZone.java
- src/test/java/uk/gov/justice/digital/zone/CuratedZoneTest.java
- src/test/java/uk/gov/justice/digital/zone/Fixtures.java
- src/test/java/uk/gov/justice/digital/zone/RawZoneTest.java
- src/test/java/uk/gov/justice/digital/zone/StructuredZoneFixture.java
- src/test/java/uk/gov/justice/digital/zone/StructuredZoneTest.java
This PR:
- Applies the incremental/CDC events to the structured zone
- The CDC events are applied (inserted/updated/deleted) on a row-by-row basis
- In case a row operation fails, the row data and destination table are logged without failing the spark job
> DPR-311: Apply CDC events to structured zone

- build.gradle
- src/it/java/uk/gov/justice/digital/converter/dms/DMS_3_4_6_ConverterIntegrationTest.java
- src/it/java/uk/gov/justice/digital/zone/StructuredZoneIntegrationTest.java
- src/test/java/uk/gov/justice/digital/zone/CuratedZoneTest.java
- src/test/java/uk/gov/justice/digital/zone/Fixtures.java
- src/test/java/uk/gov/justice/digital/zone/RawZoneTest.java
- src/test/java/uk/gov/justice/digital/zone/StructuredZoneFixtures.java
- src/test/java/uk/gov/justice/digital/zone/StructuredZoneTest.java
* integration tests now run when running `./gradlew integrationTest`
* configured workers for integration tests and added logging as per the test task
* corrected resource path names in DMS test
* temporarily disabled failing test (Kolade has a fix for this in a separate PR)
* reinstated use of classes for static fixture constants (See Effective Java)
> DPR-447 integration tests now run plus some minor refactoring

- .circleci/config.yml
* use separate cache keys for owasp and build tasks with descriptive key names
* enable owasp task on PR builds
> NOJIRA owasp run during main build should use separate cache key

- src/main/java/uk/gov/justice/digital/service/DataStorageService.java
* prevent NPE on update manifest call if the current table is not a delta table
* also revised logging on `getTable` so that it makes more sense - manifest update happens elsewhere
Note - we may need to revisit this if this is a state that should cause the job to abort. For now it will just warn.
> DPR-585 update manifest only if we have a delta table

- src/main/java/uk/gov/justice/digital/zone/curated/CuratedZone.java
- src/test/java/uk/gov/justice/digital/zone/curated/CuratedZoneCdcTest.java
- src/test/java/uk/gov/justice/digital/zone/curated/CuratedZoneLoadTest.java
This PR logs a warning message and skips records where the schema could not be found during the curated zone processing.
This is to be revisited at https://dsdmoj.atlassian.net/browse/DPR-588
> DPR-198: Log and skip schema not found records in curated zone

- src/main/java/uk/gov/justice/digital/job/DataHubJob.java
- src/main/java/uk/gov/justice/digital/job/DomainRefreshJob.java
This PR logs the error and exits with a non-zero code when an irrecoverable error is encountered by the Spark job.
This was tested in sandbox on both the reporting and refresh jobs as shown in the screenshots below:
> DPR-615: Glue job failure exit code

- build.gradle
- src/main/java/uk/gov/justice/digital/job/udf/JsonValidator.java
- src/main/java/uk/gov/justice/digital/zone/structured/StructuredZone.java
- src/test/java/uk/gov/justice/digital/job/udf/JsonValidatorTest.java
This fixes the bug in the JsonValidator where nullable columns missing in the raw data were treated as mandatory.
After the fix, 
```
{
"mandatoryField": "foo"
}
```
is now treated as valid and equal to
```
{
"mandatoryField": "foo",
"nullableField": null 
}
```
> DPR-674: Fix bug in JsonValidator

- src/main/java/uk/gov/justice/digital/client/kinesis/KinesisReader.java
- src/main/java/uk/gov/justice/digital/job/DataHubJob.java
- src/main/java/uk/gov/justice/digital/provider/SparkSessionProvider.java
This PR allows a graceful shutdown of the spark streaming context when a Glue job termination is invoked.
This will prevent data loss and the Kinesis DynamoDB checkpoint from getting corrupted due to an abrupt shutdown.
> DPR-677: Set stopGracefullyOnShutdown to true

- src/main/java/uk/gov/justice/digital/domain/DomainExecutor.java
- src/main/java/uk/gov/justice/digital/job/DataHubJob.java
- src/main/java/uk/gov/justice/digital/service/DataStorageService.java
- src/main/java/uk/gov/justice/digital/service/DomainService.java
- src/test/java/uk/gov/justice/digital/domain/DomainExecutorTest.java
- src/test/java/uk/gov/justice/digital/service/DomainServiceTest.java
This PR implements incremental refresh of the domains using the incoming CDC event to know which domain to execute.
The steps are:
- For a CDC event received, get the domain definitions which contain the same source as the event
- For each domain definition found, use its SQL viewText to determine how to query the adjoining sources. e.g. if a domain definition relies on the sources `source_A` and `source_B`, and one already has `source_A` from the CDC event, one can then determine how to query the `source_B` in order to end up with `dataFrame_B` which when joined with `dataFrame_A` allows the to creation of the domain record via executing the SQL viewText.
- Delete/update/insert the domain record into s3
- Update the manifests
> DPR-262: Load adjoining row before applying view transform

- src/main/java/uk/gov/justice/digital/common/ColumnMapping.java
- src/main/java/uk/gov/justice/digital/common/SourceMapping.java
- src/main/java/uk/gov/justice/digital/domain/DomainExecutor.java
- src/main/java/uk/gov/justice/digital/domain/ViewTextProcessor.java
- src/main/java/uk/gov/justice/digital/job/DataHubJob.java
- src/main/java/uk/gov/justice/digital/service/DomainService.java
- src/test/java/uk/gov/justice/digital/domain/DomainExecutorTest.java
- src/test/java/uk/gov/justice/digital/domain/ViewTextProcessorTest.java
- src/test/java/uk/gov/justice/digital/service/DomainServiceTest.java
This PR adds support for domains with joins on multiple tables.
For example, a domain containing three tables `tableA`, `tableB` and `tableC`
Where:
1.  `tableA` has a join with `tableB` but not with `tableC`
2. `tableC` has a join with `tableB` but not with `tableA`
Since there is no direct relationship between `tableA` and `tableC` we have to go through `tableB`.
The processing steps will be:
- When a CDC record for `tableA` arrives
- Then the dataframe record for `tableB` is loaded using the CDC record for `tableA`
- And the dataframe record for `tableC` is loaded using previously loaded record for `tableB`
- And the domain is refreshed
> DPR2-123: Support viewText with three way join

- src/main/java/uk/gov/justice/digital/service/DomainService.java
- src/test/java/uk/gov/justice/digital/service/DomainServiceTest.java
This PR excludes domains tables which are not relevant to the received CDC event.
> DPR2-130: Exclude irrelevant domain tables

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/it/java/uk/gov/justice/digital/service/DataStorageServiceIntegrationTest.java
- src/it/java/uk/gov/justice/digital/service/MaintenanceServiceCompactionIntegrationTest.java
- src/it/java/uk/gov/justice/digital/service/MaintenanceServiceVacuumIntegrationTest.java
- src/it/java/uk/gov/justice/digital/test/DeltaTablesTestBase.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/job/CompactionJob.java
- src/main/java/uk/gov/justice/digital/job/VacuumJob.java
- src/main/java/uk/gov/justice/digital/service/DataStorageService.java
- src/main/java/uk/gov/justice/digital/service/MaintenanceService.java
- src/test/java/uk/gov/justice/digital/service/DataStorageServiceTest.java
- src/test/java/uk/gov/justice/digital/service/MaintenanceServiceTest.java
- Maintenance jobs can now recurse into S3 "directories" below the root to look for nested delta lake tables
- Recursing 2 levels deep works for domain (2 levels of nesting with a table in a domain, e.g. the establishment table in the establishment domain is s3://dpr-domain-development/establishment/establishment/ where s3://dpr-domain-development/ is the root)
- Still works for raw, structured, curated
> DPR2-52: Allow maintenance jobs to recurse in to S3 "directories"

- build.gradle
- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/client/kinesis/KinesisDataProvider.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/zone/raw/RawZone.java
This fixes the streaming job not ingesting events in dev after running idle for an extended period.
This provides configurable arguments to add an idle time between reads.
> DPR2-147: Fix streaming job not ingesting events after running idle

- README.md
- src/it/java/uk/gov/justice/digital/job/batchprocessing/BatchProcessorIntegrationTest.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/exception/DataStorageException.java
- src/main/java/uk/gov/justice/digital/exception/DataStorageRetriesExhaustedException.java
- src/main/java/uk/gov/justice/digital/job/batchprocessing/BatchProcessor.java
- src/main/java/uk/gov/justice/digital/service/DataStorageService.java
- src/main/java/uk/gov/justice/digital/service/ViolationService.java
- src/main/java/uk/gov/justice/digital/writer/Writer.java
- src/main/java/uk/gov/justice/digital/writer/curated/CuratedZoneCdcWriter.java
- src/main/java/uk/gov/justice/digital/writer/structured/StructuredZoneCdcWriter.java
- src/main/java/uk/gov/justice/digital/zone/curated/CuratedZoneCDC.java
- src/main/java/uk/gov/justice/digital/zone/curated/CuratedZoneLoad.java
- src/main/java/uk/gov/justice/digital/zone/raw/RawZone.java
- src/main/java/uk/gov/justice/digital/zone/structured/StructuredZoneCDC.java
- src/main/java/uk/gov/justice/digital/zone/structured/StructuredZoneLoad.java
- src/test/java/uk/gov/justice/digital/service/DataStorageServiceTest.java
- src/test/java/uk/gov/justice/digital/service/ViolationServiceTest.java
- src/test/java/uk/gov/justice/digital/zone/curated/CuratedZoneCdcTest.java
- src/test/java/uk/gov/justice/digital/zone/curated/CuratedZoneLoadTest.java
- src/test/java/uk/gov/justice/digital/zone/raw/RawZoneTest.java
- src/test/java/uk/gov/justice/digital/zone/structured/StructuredZoneCdcTest.java
- src/test/java/uk/gov/justice/digital/zone/structured/StructuredZoneLoadTest.java
- DataStorageService now throws DataStorageRetriesExhaustedException when retries exceeded instead of propagating original exception
- Introduce ViolationService to handle violations
- Catch DataStorageRetriesExhaustedException and write violations in each zone (allowing recording the zone within the violations table error message)
- Ensure DataStorageRetriesExhaustedException is propagated upwards - this also involved switching some lambda foreach, etc. out for for loops to allow checked exceptions to propagate
> DPR2-151 write violations on retry failure

- src/it/java/uk/gov/justice/digital/config/BaseSparkTest.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/domain/DomainExecutor.java
- src/main/java/uk/gov/justice/digital/domain/model/SourceReference.java
- src/main/java/uk/gov/justice/digital/service/DataStorageService.java
- src/main/java/uk/gov/justice/digital/writer/Writer.java
- src/main/java/uk/gov/justice/digital/writer/curated/CuratedZoneCdcWriter.java
- src/main/java/uk/gov/justice/digital/writer/curated/CuratedZoneLoadWriter.java
- src/main/java/uk/gov/justice/digital/writer/structured/StructuredZoneCdcWriter.java
- src/main/java/uk/gov/justice/digital/writer/structured/StructuredZoneLoadWriter.java
- src/main/java/uk/gov/justice/digital/zone/structured/StructuredZone.java
- src/test/java/uk/gov/justice/digital/service/DataStorageServiceTest.java
- src/test/java/uk/gov/justice/digital/test/Fixtures.java
- src/test/java/uk/gov/justice/digital/test/ZoneFixtures.java
- src/test/java/uk/gov/justice/digital/zone/curated/CuratedZoneCdcTest.java
- src/test/java/uk/gov/justice/digital/zone/curated/CuratedZoneLoadTest.java
- src/test/java/uk/gov/justice/digital/zone/structured/StructuredZoneCdcTest.java
- src/test/java/uk/gov/justice/digital/zone/structured/StructuredZoneLoadTest.java
This PR
- Selects the latest records in a CDC batch when there is more than one for the same primary key
- Writes the entire batch using a single merge operation
- The records are ordered by ascending timestamp so the most recent record would be applied last
> DPR2-184: Write inserts, updates and deletes in batches

- src/it/java/uk/gov/justice/digital/job/DataHubBatchJobE2ESmokeIT.java
- src/it/java/uk/gov/justice/digital/job/E2ETestBase.java
- src/it/java/uk/gov/justice/digital/job/batchprocessing/S3BatchProcessorIT.java
- src/it/java/uk/gov/justice/digital/job/cdc/TableStreamingQueryIT.java
- src/main/java/uk/gov/justice/digital/client/s3/S3DataProvider.java
- src/main/java/uk/gov/justice/digital/common/CommonDataFields.java
- src/main/java/uk/gov/justice/digital/job/DataHubBatchJob.java
- src/main/java/uk/gov/justice/digital/job/batchprocessing/S3BatchProcessor.java
- src/main/java/uk/gov/justice/digital/job/cdc/TableStreamingQuery.java
- src/main/java/uk/gov/justice/digital/job/cdc/TableStreamingQueryProvider.java
- src/test/java/uk/gov/justice/digital/common/CommonDataFieldsTest.java
- src/test/java/uk/gov/justice/digital/job/DataHubBatchJobTest.java
- src/test/java/uk/gov/justice/digital/job/batchprocessing/S3BatchProcessorTest.java
- src/test/java/uk/gov/justice/digital/job/cdc/TableStreamingQueryTest.java
- src/test/java/uk/gov/justice/digital/test/MinimalTestData.java
Also remove distinction between input source/table (e.g. oms_owner) and sourceReference source/table (e.g. nomis) since they are now unified by DMS.
> DPR2-215: Use avro actual schemas rather than inferring.

- src/main/java/uk/gov/justice/digital/job/cdc/TableStreamingQuery.java
- src/main/java/uk/gov/justice/digital/zone/structured/StructuredZoneLoadS3.java
1. This fixes the error in the streaming checkpoint path by using underscores instead of spaces.
```2023-12-01 17:39:08,978 ERROR [main] job.DataHubCdcJob (DataHubCdcJob.java:waitUntilQueryTerminates(111)): A streaming query terminated with an Exception
org.apache.spark.sql.streaming.StreamingQueryException: Query Datahub CDC nomis.offender_external_movements [id = 440bd988-eaa9-461b-8663-a318e532ccbd, runId = 4c79a356-4bd1-4cb1-81f2-213a5a1e9644] terminated with exception: s3://dpr-glue-jobs-test/checkpoint/dpr-reporting-hub-cdc-test/DataHubCdcJob/Datahub CDC nomis.offender_external_movements/sources/0/29.compact doesn't exist (latestId: 37, compactInterval: 10)
```
2. Updates the manifest for the structured zone after the batch job processing to allow querying of the delta tables in …
> DPR2-209: Fix streaming job checkpoint

- src/it/java/uk/gov/justice/digital/config/BaseSparkTest.java
- src/it/java/uk/gov/justice/digital/job/E2ETestBase.java
- src/it/java/uk/gov/justice/digital/job/batchprocessing/S3BatchProcessorIT.java
- src/it/java/uk/gov/justice/digital/service/ViolationServiceIT.java
- src/it/java/uk/gov/justice/digital/test/BaseMinimalDataIntegrationTest.java
- src/main/java/uk/gov/justice/digital/client/s3/S3DataProvider.java
- src/main/java/uk/gov/justice/digital/common/CommonDataFields.java
- src/main/java/uk/gov/justice/digital/service/ViolationService.java
- src/test/java/uk/gov/justice/digital/service/ViolationServiceTest.java
- The violations tables are currently using the schemas of the input tables. 
- This is incompatible with writing data that doesn't match the schema (in certain incompatible ways, such as data type changes). If the data doesn't match the schema then you can't write it to a table that requires that schema!
- This work changes the violations table schemas to allow violations to be written when the schema has changed in an incompatible way since the last write to violations, such as incompatible data type change
- To enable this it changes the schema of violations from that of the input table to two columns: a string containing the error and a string containing the original input converted to json.
- Added tests to show violations with different input schemas can be written to the same …
> DPR2-210: Change violations schema to support writing datatype changes to violations

- build.gradle
- src/it/java/uk/gov/justice/digital/config/BaseSparkTest.java
- src/it/java/uk/gov/justice/digital/service/ViolationServiceIT.java
- src/test/java/uk/gov/justice/digital/job/batchprocessing/CdcBatchProcessorTest.java
- src/test/java/uk/gov/justice/digital/job/batchprocessing/S3BatchProcessorTest.java
- src/test/java/uk/gov/justice/digital/job/cdc/TableStreamingQueryTest.java
- src/test/java/uk/gov/justice/digital/service/ValidationServiceTest.java
- src/test/java/uk/gov/justice/digital/service/ViolationServiceTest.java
- src/test/java/uk/gov/justice/digital/zone/curated/CuratedZoneCdcTest.java
- src/test/java/uk/gov/justice/digital/zone/curated/CuratedZoneLoadTest.java
- src/test/java/uk/gov/justice/digital/zone/structured/StructuredZoneCdcTest.java
- src/test/java/uk/gov/justice/digital/zone/structured/StructuredZoneLoadTest.java
- Change micronaut version which doesn't work in CI build
- Show more of exceptions when tests fail
- Use @Captor to avoid type erasure warning in argument captors
- Create dataframes from json column using Dataset<String> rather than deprecated RDD version
> Fix most compiler warnings and fix build failures due to micronaut version

- src/main/java/uk/gov/justice/digital/client/s3/S3DataProvider.java
- src/main/java/uk/gov/justice/digital/exception/DataProviderFailedMergingSchemasException.java
- src/main/java/uk/gov/justice/digital/exception/FailedMergingSchemas.java
- src/main/java/uk/gov/justice/digital/job/DataHubBatchJob.java
- src/test/java/uk/gov/justice/digital/client/s3/S3DataProviderTest.java
- src/test/java/uk/gov/justice/digital/job/DataHubBatchJobTest.java
- When Spark reads data it can throw a SparkException (a checked Exception type)
- It does not advertise that it throws this using the scala @throws annotation which means that the bytecode scala generates does not have the equivalent of `throws SparkException`
- This means that the java compiler does not believe the SparkException can be thrown.
- It seems that the `catch (SparkException e)` block is optimised away because Java thinks this block can never be reached.
- The previous code works when the main method is run against an environment using Intellij but does not catch the same exception for the same input data when run in Glue using a packaged jar.
- This change changes the catch to catch a broader exception type.
- It also hides away the scala - java integration nastiness inside …
> DPR2-210: Solve Scala java integration issue

- src/it/java/uk/gov/justice/digital/service/MaintenanceServiceCompactionIntegrationTest.java
- src/it/java/uk/gov/justice/digital/service/MaintenanceServiceVacuumIntegrationTest.java
- src/test/java/uk/gov/justice/digital/common/ResourcePathTest.java
- src/test/java/uk/gov/justice/digital/service/ValidationServiceSchemasMatchTest.java
- src/test/java/uk/gov/justice/digital/test/MinimalTestData.java
- src/test/java/uk/gov/justice/digital/test/ResourceLoader.java
* Use shouldX naming pattern for tests (with some using XShouldY naming pattern where it helps readability)
* Add a couple of private constructors a la Effective Java coding standards
> DPR2-33: Use shouldX (or XShouldY if needs be) in all tests.

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/job/S3FileTransferJob.java
- src/main/java/uk/gov/justice/digital/job/SwitchHiveTableJob.java
- src/main/java/uk/gov/justice/digital/service/HiveSchemaService.java
- src/test/java/uk/gov/justice/digital/job/SwitchHiveTableJobTest.java
- src/test/java/uk/gov/justice/digital/service/HiveSchemaServiceTest.java
This PR adds a Glue job which takes a config and switches the prisons hive tables to a specified s3 data location.
Example usage:
The below config points the prisons fabric tables for the `movements` domain to the `dpr-temp-reload` s3 bucket
```
--dpr.config.key: movements
--dpr.config.s3.bucket: dpr-glue-jobs-development
--dpr.target.s3.path: dpr-temp-reload
```
> DPR2-46: Implement hive table switch job

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/it/java/uk/gov/justice/digital/job/DataHubCdcJobE2ESmokeIT.java
- src/main/java/uk/gov/justice/digital/client/s3/S3FileTransferClient.java
- src/main/java/uk/gov/justice/digital/common/ConfigSourceDetails.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/job/S3DataDeletionJob.java
- src/main/java/uk/gov/justice/digital/job/S3FileTransferJob.java
- src/main/java/uk/gov/justice/digital/service/S3FileService.java
- src/test/java/uk/gov/justice/digital/job/S3DataDeletionJobTest.java
- src/test/java/uk/gov/justice/digital/job/S3FileTransferJobTest.java
- src/test/java/uk/gov/justice/digital/service/S3FileServiceTest.java
- src/test/java/uk/gov/justice/digital/test/Fixtures.java
This PR adds two jobs:
1. `S3FileTransferJob`: moves parquet files from a source bucket to a destination bucket
```
--dpr.config.key // key for the domain config
--dpr.config.s3.bucket // s3 bucket containing the domain config
--dpr.file.transfer.source.bucket // s3 bucket where files are to me moved from
--dpr.file.transfer.destination.bucket // s3 bucket where files are to me moved to
--dpr.file.transfer.retention.days // files older than the number of days will be moved. Moves all files when omitted
```
2. `S3DataDeletionJob`: deletes parquet files from a list of bucket(s)
```
--dpr.config.key // key for the domain config
--dpr.config.s3.bucket // s3 bucket containing the domain config
--dpr.file.deletion.buckets // comma separated list of buckets from which to delete files
```
> DPr2-45: Add file transfer and data deletion jobs

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/client/glue/GlueClient.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/exception/GlueClientException.java
- src/main/java/uk/gov/justice/digital/job/StopGlueInstanceJob.java
- src/main/java/uk/gov/justice/digital/service/GlueOrchestrationService.java
- src/main/java/uk/gov/justice/digital/service/HiveSchemaService.java
- src/test/java/uk/gov/justice/digital/client/glue/GlueClientTest.java
- src/test/java/uk/gov/justice/digital/job/StopGlueInstanceJobTest.java
- src/test/java/uk/gov/justice/digital/service/GlueOrchestrationServiceTest.java
- src/test/java/uk/gov/justice/digital/service/HiveSchemaServiceTest.java
This PR migrates the StopGlueJobLambda to a glue job StopGlueInstanceJob.
This prevents lambda timeout errors and also provide automatic sync thereby eliminating the need to make a callback to the step functions.
The job takes the below args:
```
--dpr.stop.glue.instance.job.name // the name of the Glue job to stop
--dpr.glue.orchestration.wait.interval.seconds // wait interval between checks that the glue job has stopped. Defaults to 10 seconds
--dpr.glue.orchestration.max.attempts // max attempts to check the job state. Defaults to 20
```
> DPR2-46: Add stop glue instance job

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/client/s3/S3FileTransferClient.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/job/S3DataDeletionJob.java
- src/main/java/uk/gov/justice/digital/job/S3FileTransferJob.java
- src/main/java/uk/gov/justice/digital/service/HiveSchemaService.java
- src/main/java/uk/gov/justice/digital/service/S3FileService.java
- src/test/java/uk/gov/justice/digital/job/S3DataDeletionJobTest.java
- src/test/java/uk/gov/justice/digital/job/S3FileTransferJobTest.java
- src/test/java/uk/gov/justice/digital/service/HiveSchemaServiceTest.java
- src/test/java/uk/gov/justice/digital/service/S3FileServiceTest.java
This PR:
- Adds a flag on whether the S3 file transfer job should also delete copied objects
- Makes the config key optional for the S3 file transfer job. When not provides all files are transferred. This is used in the case of the scheduled job which archives all files older than 2 days
> DPR2-46: Add copy only mode for file transfer job

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/client/glue/GlueClient.java
- src/main/java/uk/gov/justice/digital/client/s3/S3FileTransferClient.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/job/S3DataDeletionJob.java
- src/main/java/uk/gov/justice/digital/job/S3FileTransferJob.java
- src/main/java/uk/gov/justice/digital/service/ConfigService.java
- src/main/java/uk/gov/justice/digital/service/GlueOrchestrationService.java
- src/main/java/uk/gov/justice/digital/service/S3FileService.java
- src/test/java/uk/gov/justice/digital/client/glue/GlueClientTest.java
- src/test/java/uk/gov/justice/digital/client/s3/S3FileTransferClientTest.java
- src/test/java/uk/gov/justice/digital/job/S3DataDeletionJobTest.java
- src/test/java/uk/gov/justice/digital/job/S3FileTransferJobTest.java
- src/test/java/uk/gov/justice/digital/service/S3FileServiceTest.java
This PR:
Makes the file copy/delete job configurable for multiple file types by supplying a comma separated list of extensions e.g. `.parquet,.json,.txt`. When a wildcard `*` is given or the list contains a wildcard then all files are processed.
> DPR2-46: Make s3 file copy accept a list of extensions

- src/main/java/uk/gov/justice/digital/job/HiveTableCreationJob.java
- src/main/java/uk/gov/justice/digital/job/SwitchHiveTableJob.java
- src/main/java/uk/gov/justice/digital/service/HiveTableService.java
- src/test/java/uk/gov/justice/digital/job/HiveTableCreationJobTest.java
- src/test/java/uk/gov/justice/digital/job/SwitchHiveTableJobTest.java
- src/test/java/uk/gov/justice/digital/service/HiveTableServiceTest.java
This PR:
- Updates the delta manifest so the prisons table is still queryable after it has been switched to use the data located in the temp-reload bucket
- Renames HiveSchemaService to HiveTableService
> DPR2-46: Update manifest after switching prisons data source

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/client/s3/S3FileTransferClient.java
- src/main/java/uk/gov/justice/digital/client/s3/S3SchemaClient.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/service/S3FileService.java
- src/test/java/uk/gov/justice/digital/client/s3/S3FileTransferClientTest.java
- src/test/java/uk/gov/justice/digital/client/s3/S3SchemaClientTest.java
This PR fixes a bug in the pagination when listing objects in S3.
To make the pagination work, the nextMarker of the current page is used to retrieve the next page.
This PR also exposed an argument `dpr.s3.max.page.size` which can be used to override the page size.
> DPR2-387: Fix pagination issue in s3 object listing

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/job/DataHubCdcJob.java
This PR adds an optional boolean flag `--dpr.clean.cdc.checkpoint` which when `true` deletes the checkpoint thereby allowing already processed files to be reprocessed. When omitted the flag defaults to `false`.
This is added to support the replay pipeline and enables reprocessing of already processed files.
> DPR2-46: Add optional flag to delete checkpoint

- src/it/java/uk/gov/justice/digital/converter/avro/AvroToSparkSchemaConverterIntegrationTest.java
- src/main/java/uk/gov/justice/digital/client/s3/S3ConfigReaderClient.java
- src/main/java/uk/gov/justice/digital/common/CommonDataFields.java
- src/main/java/uk/gov/justice/digital/converter/avro/AvroToSparkSchemaConverter.java
- src/main/java/uk/gov/justice/digital/service/ValidationService.java
- src/test/java/uk/gov/justice/digital/service/ValidationServiceTest.java
This PR:
- Uses the type specified in the metadata field validationType to validate string fields where the original datatype is not supported by spark
- The validation type metadata is configured on a field contract like below:
```
{
"name": "start_time",
"type": "string",
"nullable": false,
"metadata": {
"validationType": "time"
}
}
```
- The validationType maps to a regex validation
- Errors from invalid fields are concatenated e.g. `field_1 must have format HH:mm:ss; field_2 must have format HH:mm:ss`
- Invalid records are written as violations
> DPR2-351 Validate time field using ValidationType metadata in contract

- src/it/java/uk/gov/justice/digital/client/s3/S3DataProviderIT.java
- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/client/s3/S3DataProvider.java
- src/main/java/uk/gov/justice/digital/client/s3/S3FileTransferClient.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/job/S3DataDeletionJob.java
- src/main/java/uk/gov/justice/digital/job/S3FileTransferJob.java
- src/main/java/uk/gov/justice/digital/provider/SparkSessionProvider.java
- src/main/java/uk/gov/justice/digital/service/S3FileService.java
- src/test/java/uk/gov/justice/digital/client/s3/S3FileTransferClientTest.java
- src/test/java/uk/gov/justice/digital/job/S3DataDeletionJobTest.java
- src/test/java/uk/gov/justice/digital/job/S3FileTransferJobTest.java
- src/test/java/uk/gov/justice/digital/service/S3FileServiceTest.java
- src/test/java/uk/gov/justice/digital/test/MinimalTestData.java
This PR:
- Maintains existing behaviour by attempting to infer the schema used for the CDC batch from the raw zone 
- In case a `FileNotFoundException` occurs as a result of CDC files getting archived, it infers the schema from the raw-archive
- Increase the granularity of the duration after which a raw file is archived to allow minutes, hours or days
> DPR2-662: Infer schema from raw-zone with fallback to raw-archive

- src/main/java/uk/gov/justice/digital/client/glue/GlueClient.java
- src/main/java/uk/gov/justice/digital/common/CommonDataFields.java
- src/main/java/uk/gov/justice/digital/service/HiveTableService.java
- src/main/java/uk/gov/justice/digital/service/ValidationService.java
- src/test/java/uk/gov/justice/digital/client/glue/GlueClientTest.java
- src/test/java/uk/gov/justice/digital/service/HiveTableServiceTest.java
- src/test/java/uk/gov/justice/digital/service/ValidationServiceTest.java
- src/test/java/uk/gov/justice/digital/test/MinimalTestData.java
This PR
- Annotates the primary key(s) with the text `primary_key` when creating the Hive tables
- Adds the columns `checkpoint_col` and `update_type` to the in-memory schema to allow successful schema validation. This is required because the raw data being validated now contains both columns
[link to Hive table in dev](https://eu-west-2.console.aws.amazon.com/glue/home?region=eu-west-2#/v2/data-catalog/tables/view/nomis_staff_user_accounts?database=raw_archive&catalogId=771283872747&versionId=latest)
> DPR2-712: Annotate primary_key and handle checkpoint_col and update_type columns during validation

- build.gradle
- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/client/dms/DmsClient.java
- src/main/java/uk/gov/justice/digital/client/dms/DmsClientProvider.java
- src/main/java/uk/gov/justice/digital/client/s3/S3ObjectClient.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/exception/DmsClientException.java
- src/main/java/uk/gov/justice/digital/job/StopDmsTaskJob.java
- src/main/java/uk/gov/justice/digital/service/DmsOrchestrationService.java
- src/main/java/uk/gov/justice/digital/service/GlueOrchestrationService.java
- src/test/java/uk/gov/justice/digital/client/dms/DmsClientTest.java
- src/test/java/uk/gov/justice/digital/job/StopDmsTaskJobTest.java
- src/test/java/uk/gov/justice/digital/service/DmsOrchestrationServiceTest.java
- src/test/java/uk/gov/justice/digital/service/GlueOrchestrationServiceTest.java
This PR adds a Glue job to enable stopping a DMS task.
This job will be invoked during the reload and replay pipelines.
> DPR2-713: Add job to stop DMS task

- src/main/java/uk/gov/justice/digital/client/glue/GlueClient.java
- src/main/java/uk/gov/justice/digital/common/CommonDataFields.java
- src/main/java/uk/gov/justice/digital/service/HiveTableService.java
- src/main/java/uk/gov/justice/digital/service/ValidationService.java
- src/test/java/uk/gov/justice/digital/client/glue/GlueClientTest.java
- src/test/java/uk/gov/justice/digital/service/HiveTableServiceTest.java
- src/test/java/uk/gov/justice/digital/service/ValidationServiceTest.java
- src/test/java/uk/gov/justice/digital/test/MinimalTestData.java
This PR
- Removes the `update_type` column as it is no longer required for the AP integration
- Adds the `checkpoint_col` to the extraction key when creating the hive tables
> DPR2-712: Update AP integration fields

- src/it/java/uk/gov/justice/digital/job/DataHubBatchJobE2ESmokeIT.java
- src/it/java/uk/gov/justice/digital/job/batchprocessing/BatchProcessorIT.java
- src/it/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreServiceIntegrationTest.java
- src/main/java/uk/gov/justice/digital/service/operationaldatastore/DisabledOperationalDataStoreService.java
- src/main/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreConnectionDetailsService.java
- src/main/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreService.java
- src/main/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreServiceImpl.java
- src/test/java/uk/gov/justice/digital/job/batchprocessing/BatchProcessorTest.java
- src/test/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreConnectionDetailsServiceTest.java
- src/test/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreServiceTest.java
- Simplify operational datastore feature flag by using micronaut conditional DI instead of conditional
- Inject either a OperationalDataStoreServiceImpl or a DisabledOperationalDataStoreService implementation of OperationalDataStoreService depending on presence or absence of property "dpr.operational.data.store.write.enabled"
- This will be simpler, especially as CDC functionality uses the operational data store
> DPR2-895: Use micronaut to enable or disable operational datastore functionality

- build.gradle
- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/it/java/uk/gov/justice/digital/job/DataHubBatchJobE2ESmokeIT.java
- src/it/java/uk/gov/justice/digital/job/DataHubCdcJobE2ESmokeIT.java
- src/it/java/uk/gov/justice/digital/job/E2ETestBase.java
- src/it/java/uk/gov/justice/digital/job/batchprocessing/BatchProcessorIT.java
- src/it/java/uk/gov/justice/digital/job/cdc/TableStreamingQueryIT.java
- src/it/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreServiceIntegrationTest.java
- src/it/java/uk/gov/justice/digital/test/BaseMinimalDataIntegrationTest.java
- src/it/java/uk/gov/justice/digital/test/SharedTestFunctions.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/exception/OperationalDataStoreException.java
- src/main/java/uk/gov/justice/digital/job/batchprocessing/BatchProcessor.java
- src/main/java/uk/gov/justice/digital/job/batchprocessing/CdcBatchProcessor.java
- src/main/java/uk/gov/justice/digital/service/operationaldatastore/ConnectionPoolProvider.java
- src/main/java/uk/gov/justice/digital/service/operationaldatastore/DisabledOperationalDataStoreService.java
- src/main/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreDataAccess.java
- src/main/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreService.java
- src/main/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreServiceImpl.java
- src/main/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreTransformation.java
- src/test/java/uk/gov/justice/digital/job/batchprocessing/BatchProcessorTest.java
- src/test/java/uk/gov/justice/digital/job/batchprocessing/CdcBatchProcessorTest.java
- src/test/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreDataAccessTest.java
- src/test/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreServiceTest.java
- src/test/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreTransformationTest.java
- Update the CDC job so that on each batch it:
- Writes the output of curated to a loading table (e.g. loading.offenders), overwriting any data if the table already exists.
- Runs a SQL MERGE statement to merge the data in the loading table in to the destination table, which already exists since it was created by the batch job (e.g. from loading.offenders in to nomis.offenders).
- Finally, it truncates the loading table.
- Add a JobArguments property to configure the loading schema name.
- Updated E2E and IT tests to use in-memory operational data store when testing CDC functionality
- Unit tests
- Removes some duplication from the E2E and IT tests in to SharedTestFunctions
- Moves the dropping of metadata columns out of the Operational DataStore transformer and in to the service since …
> DPR2-895: Add merge functionality to OperationalDataStoreService.

- src/it/java/uk/gov/justice/digital/test/InMemoryOperationalDataStore.java
- One of the integration tests fails in the release repo but not in the jobs repo.
- This seems to be because the release repo runs the tests in parallel using gradle and this causes some strangeness in class loading.
- I can reproduce the issue locally with `./gradlew --parallel --max-workers=4 clean build -x test`
- The changes in this PR fix the issue when run locally
- It loads the JDBC database driver explicitly for each test that uses the in memory database using Class.forName
- This shouldn't be necessary as it is the legacy way of ensuring the class is loaded but seems to fix the weird class loading issue
> DPR2-986: Load the database driver explicitly each time we start a test database.

- src/it/java/uk/gov/justice/digital/job/DataHubBatchJobE2ESmokeIT.java
- src/it/java/uk/gov/justice/digital/job/batchprocessing/BatchProcessorIT.java
- src/it/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreServiceIntegrationTest.java
- src/it/java/uk/gov/justice/digital/test/BaseMinimalDataIntegrationTest.java
- src/it/java/uk/gov/justice/digital/test/InMemoryOperationalDataStore.java
- src/it/java/uk/gov/justice/digital/test/SharedTestFunctions.java
- src/main/java/uk/gov/justice/digital/exception/OperationalDataStoreException.java
- src/main/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreServiceImpl.java
- src/main/java/uk/gov/justice/digital/service/operationaldatastore/dataaccess/OperationalDataStoreDataAccess.java
- src/test/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreServiceTest.java
- src/test/java/uk/gov/justice/digital/service/operationaldatastore/dataaccess/OperationalDataStoreDataAccessTest.java
- So far table creation has been managed by Spark.
- We will need to move to the migrations in the transfer component as materialised views are created on top of these tables.
- This PR supports this by switching the batch load from truncating and recreating a table that already exists in the ODS to just truncating the data
- It also exits with an error telling the user to create the table in the Transfer Component if it has not already been created.
- See https://dsdmoj.atlassian.net/browse/DPR2-904 for further details
> DPR2-904 truncate instead of drop

- src/it/java/uk/gov/justice/digital/client/s3/S3DataProviderIT.java
- src/it/java/uk/gov/justice/digital/client/s3/S3DataProviderNoFilesIT.java
- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/it/java/uk/gov/justice/digital/job/DataHubCdcJobE2ESmokeIT.java
- src/it/java/uk/gov/justice/digital/job/cdc/TableStreamingQueryIT.java
- src/main/java/uk/gov/justice/digital/client/s3/S3DataProvider.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
This PR makes the maxFilesPerTrigger configurable. The config defaults to 1000 which is also the default in spark streaming. This will help us lower the pressure on the raw-zone s3 bucket when there are many streaming jobs reading files from it.
> DPR2-709: Make maxFilesPerTrigger configurable

- src/main/java/uk/gov/justice/digital/job/CreateReloadDiffJob.java
- src/main/java/uk/gov/justice/digital/job/batchprocessing/ReloadDiffProcessor.java
- src/main/java/uk/gov/justice/digital/service/DataStorageService.java
- src/test/java/uk/gov/justice/digital/job/CreateReloadDiffJobTest.java
- src/test/java/uk/gov/justice/digital/job/batchprocessing/ReloadDiffProcessorTest.java
- src/test/java/uk/gov/justice/digital/service/DataStorageServiceTest.java
When the reload diff job is ran and there is no previously archived data, it creates an empty dataset with the specified contracts as its schema. This can create schema mismatch on columns where the raw dataset has a different type from that specified in the contract e.g. `tinyint` and `int` respectively.
This PR fixes this mismatch by using the inferred schema from the raw dataset instead of the schema specified in the contracts.
> DPR2-1101: Fix schema mismatch in reload diff

- src/main/java/uk/gov/justice/digital/job/DataHubCdcJob.java
- src/main/java/uk/gov/justice/digital/provider/SparkSessionProvider.java
This PR returns an exit status code of zero when an AbortedException is encountered in the CDC job (i.e when the SDK receives a signal to stop).
> DPR2-709: Return status code 0 for AbortedException

- build.gradle
- src/main/java/uk/gov/justice/digital/job/CompactionJob.java
- src/main/java/uk/gov/justice/digital/job/CreateReloadDiffJob.java
- src/main/java/uk/gov/justice/digital/job/DataHubBatchJob.java
- src/main/java/uk/gov/justice/digital/job/DataHubCdcJob.java
- src/main/java/uk/gov/justice/digital/job/DataReconciliationJob.java
- src/main/java/uk/gov/justice/digital/job/GlueTriggerActivationJob.java
- src/main/java/uk/gov/justice/digital/job/HiveTableCreationJob.java
- src/main/java/uk/gov/justice/digital/job/PicocliMicronautExecutor.java
- src/main/java/uk/gov/justice/digital/job/RawFileArchiveJob.java
- src/main/java/uk/gov/justice/digital/job/S3DataDeletionJob.java
- src/main/java/uk/gov/justice/digital/job/S3FileTransferJob.java
- src/main/java/uk/gov/justice/digital/job/StopDmsTaskJob.java
- src/main/java/uk/gov/justice/digital/job/StopGlueInstanceJob.java
- src/main/java/uk/gov/justice/digital/job/SwitchHiveTableJob.java
- src/main/java/uk/gov/justice/digital/job/UnprocessedRawFilesCheckJob.java
- src/main/java/uk/gov/justice/digital/job/VacuumJob.java
- src/test/java/uk/gov/justice/digital/job/PicocliMicronautExecutorTest.java
- Fixes a bug where if a job fails while micronaut is creating objects whilst bootstrapping the dependency injection object graph then it would return a success exit code
- This resulted in jobs appearing as successful in glue when they should be reported as failed
- Introduces a class PicocliMicronautExecutor to run the job and handle exit code because Micronaut's PicocliRunner doesn't expose the execute method we need with ApplicationContext as a parameter
- We need ApplicationContext as a parameter because of the custom MicronautContext we are using to instantiate JobArguments, etc.
> DPR2-1160: try explicit system exit with error code when exception encountered during bootstrap

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/job/DataReconciliationJob.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/ChangeDataCountService.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/CurrentStateCountService.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/DataReconciliationService.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/ChangeDataTotalCounts.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/CurrentStateTotalCounts.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/DataReconciliationResult.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/DataReconciliationResults.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/ReconciliationCheck.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/ReconciliationType.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/ChangeDataCountServiceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/CurrentStateCountServiceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/DataReconciliationServiceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/ChangeDataTotalCountsTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/CurrentStateTotalCountsTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/DataReconciliationResultsTest.java
- `dpr.reconciliation.checks.to.run` config job argument can be set to a single check or a comma separated list of checks.
- Checks available currently are `current_state_counts` and `change_data_counts` with at least one more to follow in future work
- If the job argument is not set then it defaults to the previous behaviour of running all checks
- Unify the interface for the results of a check/checks in `DataReconciliationResult`
> DPR2-1124 optional configuration for which reconciliations to run

- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/ChangeDataTotalCounts.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/ChangeDataTotalCountsTest.java
- Adds details to what is logged when the set of tables for DMS vs DMS applied vs Raw/Raw archive do not match
- Previously it just told you they did not match
- Now it lists the names of the tables in each datastore to amke it easier to work out what the problem is
> DPR2-1124 better logging when set of tables do not match

- src/main/java/uk/gov/justice/digital/client/s3/S3DataProvider.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/CurrentStateCountService.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/CurrentStateCountServiceTest.java
- Structured and Curated zones are stored in Delta format
- Therefore we need to use delta format to read them as reading them as raw parquet results in deleted rows showing up during reconciliation
- This PR changes the reconciliation of current data counts to read using delta format
> DPR2-1127: Use delta instead of parquet when reading structured and curated

- src/main/java/uk/gov/justice/digital/datahub/model/JDBCCredentials.java
- src/main/java/uk/gov/justice/digital/exception/JDBCGlueConnectionDetailsException.java
- src/main/java/uk/gov/justice/digital/job/DataReconciliationJob.java
- src/main/java/uk/gov/justice/digital/service/JDBCGlueConnectionDetailsService.java
- src/test/java/uk/gov/justice/digital/service/operationaldatastore/dataaccess/JDBCGlueConnectionDetailsServiceTest.java
During testing I saw an issue where spark used "spark" as a username in its JDBC reader. This was because the contents of a secret had a misspelling for username causing it to be set to null, and spark to default to the username "spark". This was difficult to troubleshoot because the error message was unhelpful so I have added some defensive null checks with descriptive error messages.
> DPR2-1127: Fail early with null connection or credential details

- src/main/java/uk/gov/justice/digital/client/s3/S3DataProvider.java
- src/test/java/uk/gov/justice/digital/client/s3/S3DataProviderTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/CurrentStateCountServiceTest.java
- When structured or curated tables are missing then set reconciliation count to zero
> DPR2-1135: Handle missing tables in structured/curated zones by setting count to zero.

- src/it/java/uk/gov/justice/digital/service/MaintenanceServiceCompactionIntegrationTest.java
- src/it/java/uk/gov/justice/digital/service/MaintenanceServiceVacuumIntegrationTest.java
- src/main/java/uk/gov/justice/digital/job/CompactionJob.java
- src/main/java/uk/gov/justice/digital/job/VacuumJob.java
- src/main/java/uk/gov/justice/digital/service/ConfigService.java
- src/main/java/uk/gov/justice/digital/service/MaintenanceService.java
- src/test/java/uk/gov/justice/digital/service/MaintenanceServiceTest.java
This PR makes the Compaction and Vacuum jobs configurable to run per domain by passing the `dpr.config.key` and `dpr.config.s3.bucket`. When the config key is missing then the jobs run for all tables in the given `dpr.maintenance.root.path`.
> DPR2-1105: Make vacuum and compaction jobs runnable for a domain

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/client/cloudwatch/CloudwatchClient.java
- src/main/java/uk/gov/justice/digital/client/cloudwatch/CloudwatchClientProvider.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/job/DataReconciliationJob.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/DataReconciliationService.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/DisabledReconciliationMetricReportingService.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/ReconciliationMetricReportingService.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/ReconciliationMetricReportingServiceImpl.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/ChangeDataTotalCounts.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/DataReconciliationResults.java
- src/test/java/uk/gov/justice/digital/client/cloudwatch/CloudwatchClientTest.java
- src/test/java/uk/gov/justice/digital/job/DataReconciliationJobTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/DataReconciliationServiceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/DisabledReconciliationMetricReportingServiceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/ReconciliationMetricReportingServiceImplTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/ChangeDataTotalCountsTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/DataReconciliationResultsTest.java
- Reports reconciliaiton job failures to cloudwatch metrics
- Single dimension of domain (e.g. prisoner, activities) to keep custom metric costs low (only one custom metric per input domain)
- It reports a count of how many reconciliation checks failed
> DPR2-1136: Report reconciliation failures to cloudwatch.

- src/main/java/uk/gov/justice/digital/common/retry/RetryPolicyBuilder.java
- src/main/java/uk/gov/justice/digital/service/S3FileService.java
- src/test/java/uk/gov/justice/digital/service/S3FileServiceTest.java
This PR applies the retry policy when a failure occurs while listing objects in S3. This will make the job more resilient against `503 Slow Down errors` we get from S3.
> DPR2-1240: Apply retry when listing S3 files

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/job/cdc/TableStreamingQuery.java
- src/main/java/uk/gov/justice/digital/job/cdc/TableStreamingQueryProvider.java
- src/test/java/uk/gov/justice/digital/job/cdc/TableStreamingQueryTest.java
This PR makes the spark streaming trigger interval configurable with a default of 60 seconds.
This will reduce the frequency of calls to S3 when the batch processing times are very short.
> DPR2-1500: Make spark streaming trigger interval configurable

- src/it/java/uk/gov/justice/digital/client/s3/S3DataProviderIT.java
- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/client/s3/S3DataProvider.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/datahub/model/SourceReference.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/DataReconciliationService.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/PrimaryKeyReconciliationService.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/ReconciliationDataSourceService.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/PrimaryKeyReconciliationCount.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/PrimaryKeyReconciliationCounts.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/ReconciliationCheck.java
- src/test/java/uk/gov/justice/digital/datahub/model/PrimaryKeyTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/DataReconciliationServiceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/PrimaryKeyReconciliationServiceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/ReconciliationDataSourceServiceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/PrimaryKeyReconciliationCountTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/PrimaryKeyReconciliationCountsTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/ReconciliationCheckTest.java
- Adds an optional reconciliation check to diff primary keys between data source and curated zones
- The use case is when you know other reconciliations have shown there is a mismatch in row counts and you want to pinpoint the rows that are different
- This is not included in the default reconciliations as it requires more resources
> DPR2-1133: Primary key reconciliation

- src/main/java/uk/gov/justice/digital/service/DataStorageService.java
- src/test/java/uk/gov/justice/digital/service/DataStorageServiceTest.java
This PR logs a warning message without failing when an attempt to compact or vacuum a missing delta table is made.
> DPR2-1562: Do not fail when compacting or vacuuming missing delta tables

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/client/s3/S3CheckpointReaderClient.java
- src/main/java/uk/gov/justice/digital/client/s3/S3ObjectClient.java
- src/main/java/uk/gov/justice/digital/common/RegexPatterns.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/job/RawFileArchiveJob.java
- src/main/java/uk/gov/justice/digital/job/S3DataDeletionJob.java
- src/main/java/uk/gov/justice/digital/job/S3FileTransferJob.java
- src/main/java/uk/gov/justice/digital/job/UnprocessedRawFilesCheckJob.java
- src/main/java/uk/gov/justice/digital/service/CheckpointReaderService.java
- src/main/java/uk/gov/justice/digital/service/HiveTableService.java
- src/main/java/uk/gov/justice/digital/service/S3FileService.java
- src/test/java/uk/gov/justice/digital/client/s3/S3FileTransferClientTest.java
- src/test/java/uk/gov/justice/digital/job/RawFileArchiveJobTest.java
- src/test/java/uk/gov/justice/digital/job/S3DataDeletionJobTest.java
- src/test/java/uk/gov/justice/digital/job/S3FileTransferJobTest.java
- src/test/java/uk/gov/justice/digital/job/UnprocessedRawFilesCheckJobTest.java
- src/test/java/uk/gov/justice/digital/service/CheckpointReaderServiceTest.java
- src/test/java/uk/gov/justice/digital/service/S3FileServiceTest.java
- src/test/java/uk/gov/justice/digital/test/Fixtures.java
This PR:
- Modifies the argument `dpr.allowed.s3.file.extensions` to `dpr.allowed.s3.file.regex`
- The `dpr.allowed.s3.file.extensions` argument defaults to `.+` which matches all files
- When only CDC files are to be matched the value can be set to `\\d+-\\d+.parquet`
> DPR2-1643: Allow Glue jobs accept a regex instead of a list of file extensions

- src/it/java/uk/gov/justice/digital/job/cdc/TableStreamingQueryIT.java
- src/main/java/uk/gov/justice/digital/service/ValidationService.java
- src/test/java/uk/gov/justice/digital/service/ValidationServiceTest.java
- src/test/java/uk/gov/justice/digital/test/MinimalTestData.java
When the DMS processes deletes from Oracle it includes the body of the deleted row in the record. DMS with Postgres does not do this by default (only including the primary key columns and metadata columns added by DMS) and requires configuration on the database to do so.
This PR prevents deletes that do not include the body of the deleted row from failing validation and being sent to violations so that they can be processed normally.
To do this it:
- Only validates that required columns in the schema are included for operations which aren't a Delete
- However, it still checks that primary key columns are included for Deletes as these are still required
- Adds an extra validation that the Operation column is not null
> DPR2-1633: Fix DMS Postgres Deletes going to violations.

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/CurrentStateCountService.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/ReconciliationTolerance.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/CurrentStateTableCount.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/CurrentStateCountServiceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/ReconciliationToleranceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/CurrentStateTableCountTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/CurrentStateTotalCountsTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/DataReconciliationResultsTest.java
- Adds a configurable absolute tolerance and a relative percentage tolerance for the current_state_counts reconciliation check. You can choose to use one or the other, both or neither.
- Setting a tolerance means the values do not have to match exactly and can be slightly different. This is useful because often during CDC processing timing issues in the data flowing between systems will result in counts being slightly different. E.g. A data point is registered in DSM but not committed to S3 yet.
- Both tolerance settings default to zero which preserves the current behaviour of not allowing any tolerance and requiring exact matches in counts to pass reconciliation.
- Set with `dpr.reconciliation.changedatacounts.tolerance.absolute` and …
> DPR2-1702: Add reconciliation tolerance to current state table counts reconciliation

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/CurrentStateCountService.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/DmsChangeDataCountService.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/RawChangeDataCountService.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/ChangeDataTableCount.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/ChangeDataTotalCounts.java
- src/main/java/uk/gov/justice/digital/service/datareconciliation/model/CurrentStateTableCount.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/ChangeDataCountServiceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/CurrentStateCountServiceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/DmsChangeDataCountServiceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/RawChangeDataCountServiceTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/ChangeDataTableCountTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/ChangeDataTotalCountsTest.java
- src/test/java/uk/gov/justice/digital/service/datareconciliation/model/DataReconciliationResultsTest.java
Adds configurable tolerance for the change data counts reconciliation check. For background see https://github.com/ministryofjustice/digital-prison-reporting-jobs/pull/358 for details of how tolerance works in the context of another data reconciliation check
> DPR2-1702: Add tolerance to change data counts reconciliation

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/job/RawFileArchiveJob.java
- src/test/java/uk/gov/justice/digital/job/RawFileArchiveJobTest.java
Spark structured streaming commits file(s) to its checkpoint as soon as it picks them up. This leads to the scenario where check-pointed files may be moved by the archiving job before the processing is finished. This may lead to data loss i.e less records making it to the curated zone.
To avoid the aforementioned scenario, this PR modifies the `RawFileArchiveJob` so:
- It deletes raw files which have been check-pointed and are older than a configurable number of days (default is 2 days)
- It copies check-pointed files to the archive bucket without deleting the raw files
> DPR2-1684: Delete old files and copy recent ones to archive

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/client/s3/S3CheckpointReaderClient.java
- src/main/java/uk/gov/justice/digital/client/s3/S3ObjectClient.java
- src/main/java/uk/gov/justice/digital/common/ListObjectsConfig.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/datahub/model/FileLastModifiedDate.java
- src/main/java/uk/gov/justice/digital/datahub/model/ListObjectsConfig.java
- src/main/java/uk/gov/justice/digital/job/RawFileArchiveJob.java
- src/main/java/uk/gov/justice/digital/job/S3DataDeletionJob.java
- src/main/java/uk/gov/justice/digital/job/S3FileTransferJob.java
- src/main/java/uk/gov/justice/digital/job/UnprocessedRawFilesCheckJob.java
- src/main/java/uk/gov/justice/digital/service/CheckpointReaderService.java
- src/main/java/uk/gov/justice/digital/service/S3FileService.java
- src/test/java/uk/gov/justice/digital/client/s3/S3CheckpointReaderClientTest.java
- src/test/java/uk/gov/justice/digital/client/s3/S3ClientTest.java
- src/test/java/uk/gov/justice/digital/job/RawFileArchiveJobTest.java
- src/test/java/uk/gov/justice/digital/job/S3DataDeletionJobTest.java
- src/test/java/uk/gov/justice/digital/job/S3FileTransferJobTest.java
- src/test/java/uk/gov/justice/digital/job/UnprocessedRawFilesCheckJobTest.java
- src/test/java/uk/gov/justice/digital/service/CheckpointReaderServiceTest.java
- src/test/java/uk/gov/justice/digital/service/S3FileServiceTest.java
The archive job:
1. Archives raw files which have not been previously archived
2. Deletes all raw files which have been committed to the checkpoint and are older than 2 days (configurable)
To avoid wasting cost on re-archiving already archived files, the raw files are checked to ensure they do not have an existing key in the list of most recent archived files up until the last 2 days (configurable)
> DPR2-1684: Ignore already archived files

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/it/java/uk/gov/justice/digital/job/DataHubBatchJobE2ESmokeIT.java
- src/it/java/uk/gov/justice/digital/job/DataHubCdcJobE2ESmokeIT.java
- src/it/java/uk/gov/justice/digital/job/batchprocessing/BatchProcessorIT.java
- src/it/java/uk/gov/justice/digital/job/cdc/TableStreamingQueryIT.java
- src/it/java/uk/gov/justice/digital/service/operationaldatastore/OperationalDataStoreServiceIntegrationTest.java
- src/it/java/uk/gov/justice/digital/service/operationaldatastore/dataaccess/OperationalDataStoreRepositoryIntegrationTest.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/config/JobProperties.java
- src/main/java/uk/gov/justice/digital/job/CompactionJob.java
- src/main/java/uk/gov/justice/digital/job/CreateReloadDiffJob.java
- src/main/java/uk/gov/justice/digital/job/DataHubBatchJob.java
- src/main/java/uk/gov/justice/digital/job/DataHubCdcJob.java
- src/main/java/uk/gov/justice/digital/job/DataReconciliationJob.java
- src/main/java/uk/gov/justice/digital/job/SparkJobRunner.java
- src/main/java/uk/gov/justice/digital/job/SwitchHiveTableJob.java
- src/main/java/uk/gov/justice/digital/job/VacuumJob.java
- src/main/java/uk/gov/justice/digital/provider/SparkSessionProvider.java
- src/main/java/uk/gov/justice/digital/service/operationaldatastore/dataaccess/OperationalDataStoreRepository.java
- src/test/java/uk/gov/justice/digital/config/BaseSparkTest.java
- src/test/java/uk/gov/justice/digital/config/JobPropertiesTest.java
- src/test/java/uk/gov/justice/digital/job/CompactionJobTest.java
- src/test/java/uk/gov/justice/digital/job/SwitchHiveTableJobTest.java
- src/test/java/uk/gov/justice/digital/job/VacuumJobTest.java
This PR creates a `dpr.adjust.spark.memory` flag to enable adjusting the memory used by the spark job to a higher value.
The flag defaults to false thereby maintaining default memory value i.e. the value injected by glue.
When the flag is set to true, the spark memory is adjusted to 0.75% instead of 0.625% of the Glue worker memory. This gives spark jobs which are spilling to disk more memory to work with.
> DPR2-1774: Configure spark memory using worker type

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/provider/SparkSessionProvider.java
- Added configurable spark.sql.files.maxRecordsPerFile to avoid the problem of very large files when the CDC job processes a large backlog.
- This defaults to 0 (unlimited) as before so there is no change unless it is explicitly set to another value. 
- We can configure this on CDC jobs in the domains repo to a reasonable finger in the air value and then override it for specific pipelines as needed.
> DPR2-1930: Make spark.sql.files.maxRecordsPerFile configurable with a default

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/it/java/uk/gov/justice/digital/job/generator/PostgresLoadGeneratorJobTest.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/main/java/uk/gov/justice/digital/datahub/model/generator/DataGenerationConfig.java
- src/main/java/uk/gov/justice/digital/datahub/model/generator/PostgresSecrets.java
- src/main/java/uk/gov/justice/digital/job/generator/PostgresLoadGeneratorJob.java
This is a Glue job which was created for testing purposes to insert records into a Postgres instance.
The job takes the arguments below:
- `dpr.test.database.secret.id`: The identity of the secrets containing the connection to the database
- `dpr.test.data.batch.size`: The number of records to be inserted in one query
- `dpr.test.data.parallelism`: The minimum number of batches to be written 
- `dpr.test.data.inter.batch.delay.millis`: The amount of delay between each batch execution
- `dpr.test.data.run.duration.millis`: The total run duration of the job invocation
> DPR2-1884: Create PostgresLoadGeneratorJob

- src/main/java/uk/gov/justice/digital/service/operationaldatastore/dataaccess/OperationalDataStoreDataAccessService.java
- src/test/java/uk/gov/justice/digital/service/operationaldatastore/dataaccess/OperationalDataStoreDataAccessServiceTest.java
When we have a table managed in the Operational Datastore that contains only primary key columns then the CDC job fails when trying to merge the data in. The Batch job is unaffected.
For example, the `prisonregister_prison_category` table is affected because it has only 2 columns which together make up a composite primary key.
The cause is that our code expects there to be non-primary key columns that require an update. Because there are no primary key columns we end up with an empty set of columns after `THEN UPDATE SET`(see below). 
```
MERGE INTO prisons.prisonregister_prison_category destination
USING loading.prisonregister_prison_category source ON source.category = destination.category and source.prison_id = destination.prison_id
WHEN MATCHED AND source.op = 'D' THEN DELETE
WHEN …
```
> DHS-409: Fix CDC merge into ODS when a table only has primary key columns

- src/main/java/uk/gov/justice/digital/exception/BackfillException.java
- src/main/java/uk/gov/justice/digital/job/ArchiveBackfillJob.java
- src/main/java/uk/gov/justice/digital/job/batchprocessing/ArchiveBackfillProcessor.java
- src/test/java/uk/gov/justice/digital/job/ArchiveBackfillJobTest.java
- src/test/java/uk/gov/justice/digital/job/batchprocessing/ArchiveBackfillProcessorTest.java
This PR updates the reload job to handle permitted schema changes.
- When nullable columns are added to the schema, the reload job computes a back-filled version of the archive data by adding null values for the columns and then writes the result to a temp location in S3
- The original archive data will then be replaced by the back-filled version during the reload pipeline
- When a non-nullable column is added, the job fails since we would not know what default to use for the column. This scenario will require a re-ingestion.
- When a nullable column is removed the pipeline will fail because we do not know if a removed column is nullable without schema versioning which we have not implemented yet
> DHS-411: Handle addition of nullable column(s)

- src/it/java/uk/gov/justice/digital/config/JobArgumentsIntegrationTest.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
The clustered domain takes longer when stopping the DMS task thereby causing the maintenance pipeline to fail. To prevent this, the overall wait period can be increased by further increasing `dpr.orchestration.max.attempts` to a default value of 40.
> DHS-447: Increase the default dpr.orchestration.max.attempts to 40

- src/main/java/uk/gov/justice/digital/client/s3/S3SchemaClient.java
- src/main/java/uk/gov/justice/digital/config/JobArguments.java
- src/test/java/uk/gov/justice/digital/client/s3/S3SchemaClientTest.java
This PR adds retries with backoff on failure when retrieving the hive schemas. This is to make the glue jobs more resilient to failures e.g. ThrottlingException which may occur when getting the schemas.
> DHS-460: Retry on schema retrieval failure
